import './global.css';
import { LiveAnnouncerRoot } from '../components/a11y/LiveAnnouncerRoot';

export const metadata = {
  title: 'Welcome to practitioner',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <LiveAnnouncerRoot>
          <main>{children}</main>
        </LiveAnnouncerRoot>
      </body>
    </html>
  );
}
